music = read.csv("music.csv")
head(music)
lang = read.csv("language.csv")
d = rbind(music,lang)
d
summary(d)
head( d %>% separate("condition",c("type","condition","position"),sep='/'))
library(dplyr)
head( d %>% separate("condition",c("type","condition","position"),sep='/'))
library(tidyr)
head( separate(d,"condition",c("type","condition","position"),sep='/'))
d <-  separate(d,"condition",c("type","condition","position"),sep='/')
m <- lm(mean ~ channel*type, subset(d, wname == "N400" & position == "onset" & condition == "target"))
summary(m)
head(spread(d, wname, mean))
d.wide <- spread(d, wname, mean)
m <- lm(N400 ~ channel*type*baseline, subset(d.wide, position == "onset" & condition == "target"))
m <- lm(N400 ~ channel*type*baseline, subset(d.wide, position == "onset" & condition == "target"),na.action=na.exclude)
m <- lm(N400 ~ channel*type + baseline, subset(d.wide, position == "onset" & condition == "target"),na.action=na.exclude)
m <- lm(N400 ~ channel*type + baseline, subset(d.wide, condition == "target"),na.action=na.exclude)
m <- lm(N400 ~ channel*type, subset(d.wide, position == "onset" & condition == "target"),na.action=na.exclude)
d.wide <- spread(d[,-"win"], wname, mean)
colnames(d)
colnames(d)[7]
d.wide <- spread(d[,-c(6)], wname, mean)
head(d.wide)
d.wide
head(d.wide,100)
m <- lm(N400 ~ channel*type, subset(d.wide, position == "onset" & condition == "target"),na.action=na.exclude)
library(car)
Anova(m)
Anova(lm(P100 ~ channel*type, subset(d.wide, position == "onset" & condition == "target"),na.action=na.exclude))
Anova(lm(00 ~ channel*type, subset(d.wide, position == "onset" & condition == "target"),na.action=na.exclude))
Anova(lm(N200 ~ channel*type, subset(d.wide, position == "onset" & condition == "target"),na.action=na.exclude))
history
history()
?history()
?history()
history('linear_model.R')
?history()
savehistory('linear_model.R')
